apiVersion: v1
kind: Service
metadata:
  namespace: lendasbet-stg
  name: lendasbet-frontend-stable
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    app: lendasbet-frontend-stable