apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lendasbet-stg
  labels:
    app: lendasbet-frontend
  name: lendasbet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lendasbet-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: lendasbet-frontend
    spec:
      containers:
        - image: 229131829469.dkr.ecr.us-east-1.amazonaws.com/lendasbet-frontend-stg:latest
          name: lendasbet-frontend
          ports:
            - containerPort: 3000
          resources:
            limits: 
              cpu: 0.5
              memory: 1G
            requests:
              cpu: 0.5
              memory: 1G
      restartPolicy: Always