---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: lendasbet-stg
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
    
        location = /health {
                access_log off;
                add_header 'Content-Type' 'application/json';
                return 200 '{"status":"UP"}';
        }
        
        location / {
          # Authentication
                  auth_basic "Restricted Content";
                  auth_basic_user_file /etc/nginx/.htpasswd;
          # Reverse proxy config
                  proxy_pass http://lendasbet-frontend.lendasbet-stg.svc.cluster.local:3000;
                  #proxy_bind              $server_addr;
                  proxy_set_header        Host $host;
                  proxy_set_header        X-Real-Ip $remote_addr;
                  proxy_set_header        X-Forward-For $proxy_add_x_forwarded_for;
                  proxy_set_header        Connection keep-alive;
                  proxy_set_header        Origin "$scheme://$host";
          }
          location /api/payments/notify {
                  proxy_pass http://lendasbet-frontend.lendasbet-stg.svc.cluster.local:3000;
                  proxy_set_header        Host $host;
                  proxy_set_header        X-Real-Ip $remote_addr;
                  proxy_set_header        X-Forward-For $proxy_add_x_forwarded_for;
                  proxy_set_header        Connection keep-alive;
                  proxy_set_header        Origin "$scheme://$host";
          }
    }
  robots.txt: |
    User-agent: *
    Disallow:/
    Sitemap:
    https://staging.lendasbet.com/sitemap.xml
  
  .htpasswd: |
    admin:$apr1$wZrbdcq2$NE1m9fzUdqCCyeb.lj0lc/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lendasbet-stg
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.25.2
          name: nginx
          ports:
            - containerPort: 80
          resources:
            limits: 
              cpu: 0.5
              memory: 1G
            requests:
              cpu: 0.5
              memory: 1G
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx-claim
            - mountPath: /app/public/robots.txt
              subPath: robots.txt
              name: nginx-claim
            - mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
              name: nginx-claim
      restartPolicy: Always
      volumes:
        - name: nginx-claim
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
              - key: robots.txt
                path: robots.txt
              - key: .htpasswd
                path: .htpasswd

---
apiVersion: v1
kind: Service
metadata:
  namespace: lendasbet-stg
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
  selector:
    app: nginx